baseName: db-large
replicaCount: 2  # Default to 1
replicas: 3
resources:
  limits:
    cpu: '8.0'
    memory: 32Gi
  requests:
    cpu: '8.0'
    memory: 32Gi
enclosureSpread: false  # Set to false to disable
nodeSpread: true  # Set to false to disable